# This program is not menu driven

# public p and g 
p = 42
g = 5

# generating individual secret key for sender and reciever 
def SenderSide(a): # A
    return (g ** a) % p

def RecieverSide(b): # B
    return (g ** b)%p

# secret key A and B are shared :)

def ReciverSideKeyGeneration(A , b):
    s = (A ** b) % p
    return s

def SenderSideKeyGeneration(B , a):
    s = (B ** a) % p
    return s

# the key s generated by fucntion SenderSideKeyGeneration and ReciverSideKeyGeneration are same and can be used to encrypt 
def __main__():
    sendKe = SenderSide(4) # A
    reciveKe = RecieverSide(3) # B
    seKeE = SenderSideKeyGeneration(reciveKe,4)
    reKeE = ReciverSideKeyGeneration(sendKe,3)
    if(reKeE == seKeE):
        print(True)
        print("Generated Secret Keys are the same.")
    else:
        print("Get good")

__main__()